# Generated by Django 5.2.1 on 2025-06-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_sub",
            field=models.BooleanField(default=False),
        ),
    ]
